input_clusters_topic: "laser_overlap_trace/clusters" #"laser_clustering/clusters" #"laser_overlap_trace/clusters"
results4meters_topic: "~results4meters"
frame_id: "laser_link"
classifier_file: "LDA_classifier.p" #place the file inside the classification_files folder.
publish_viz: False
viz_topic: "~viz_req"
dt: 25
human_speed: 5
timewindow: 40
distance: 4	#defined in meters
