input_clusters_topic: "laser_clustering/clusters"
results4meters_topic: "results4meters"
frame_id: "laser_link"
classifier_file: "LDA_classifier.p" #place the file inside the classification_files folder.
publish_viz: False
viz_topic: "viz_req"